# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-28 10:36
from __future__ import unicode_literals

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('list_of_books', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=books.models.upload_location_authors)),
                ('email_id', models.CharField(blank=True, max_length=30)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('writing_field', models.CharField(blank=True, choices=[('Science fiction', 'Science fiction'), ('Satire', 'Satire'), ('Drama', 'Drama'), ('Action and Adventure', 'Action and Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Self help', 'Self help'), ('Health', 'Health'), ('Guide', 'Guide'), ('Travel', 'Travel'), ("Children's", "Children's"), ('Religion, Spirituality & New Age', 'Religion, Spirituality & New Age'), ('Science', 'Science'), ('History', 'History'), ('Math', 'Math'), ('Anthology', 'Anthology'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer books', 'Prayer books'), ('Series', 'Series'), ('Trilogy', 'Trilogy'), ('Biographies', 'Biographies'), ('Autobiographies', 'Autobiographies'), ('Fantasy', 'Fantasy')], max_length=20)),
                ('youtube_video', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='book_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('image', models.FileField(blank=True, null=True, upload_to=books.models.upload_location_books)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Science fiction', 'Science fiction'), ('Satire', 'Satire'), ('Drama', 'Drama'), ('Action and Adventure', 'Action and Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Self help', 'Self help'), ('Health', 'Health'), ('Guide', 'Guide'), ('Travel', 'Travel'), ("Children's", "Children's"), ('Religion, Spirituality & New Age', 'Religion, Spirituality & New Age'), ('Science', 'Science'), ('History', 'History'), ('Math', 'Math'), ('Anthology', 'Anthology'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer books', 'Prayer books'), ('Series', 'Series'), ('Trilogy', 'Trilogy'), ('Biographies', 'Biographies'), ('Autobiographies', 'Autobiographies'), ('Fantasy', 'Fantasy')], max_length=20)),
                ('author_name', models.CharField(blank=True, max_length=30)),
                ('isbn_number', models.CharField(blank=True, max_length=30)),
                ('mrp', models.IntegerField(blank=True)),
                ('discount', models.IntegerField(blank=True)),
                ('selling_price', models.IntegerField(blank=True)),
                ('preview', models.FileField(blank=True, null=True, upload_to=books.models.upload_location_books)),
                ('book', models.FileField(blank=True, null=True, upload_to=books.models.upload_location_books)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
