# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-30 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170628_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_detail',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
