# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-30 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170630_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author_detail',
            old_name='photo1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='author_detail',
            old_name='photo2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='author_detail',
            old_name='photo3',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='book_detail',
            old_name='image4',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='book_detail',
            old_name='image5',
            new_name='front_image',
        ),
    ]
