# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-30 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170630_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_detail',
            old_name='background_image',
            new_name='back_image',
        ),
    ]
