# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-09 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='user_email',
        ),
    ]
