# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-09 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170709_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='garuda_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_feed', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
