# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_garuda_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_detail',
            name='competitive_exam',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='new_release',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='upcoming_book',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='author_detail',
            name='writing_field',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Competitive', 'Competitive'), ('Science fiction', 'Science fiction'), ('Satire', 'Satire'), ('Drama', 'Drama'), ('Action and Adventure', 'Action and Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Self help', 'Self help'), ('Health', 'Health'), ('Guide', 'Guide'), ('Travel', 'Travel'), ("Children's", "Children's"), ('Religion, Spirituality & New Age', 'Religion, Spirituality & New Age'), ('Science', 'Science'), ('History', 'History'), ('Math', 'Math'), ('Anthology', 'Anthology'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer books', 'Prayer books'), ('Series', 'Series'), ('Trilogy', 'Trilogy'), ('Biographies', 'Biographies'), ('Autobiographies', 'Autobiographies'), ('Fantasy', 'Fantasy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='category',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Competitive', 'Competitive'), ('Science fiction', 'Science fiction'), ('Satire', 'Satire'), ('Drama', 'Drama'), ('Action and Adventure', 'Action and Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Self help', 'Self help'), ('Health', 'Health'), ('Guide', 'Guide'), ('Travel', 'Travel'), ("Children's", "Children's"), ('Religion, Spirituality & New Age', 'Religion, Spirituality & New Age'), ('Science', 'Science'), ('History', 'History'), ('Math', 'Math'), ('Anthology', 'Anthology'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer books', 'Prayer books'), ('Series', 'Series'), ('Trilogy', 'Trilogy'), ('Biographies', 'Biographies'), ('Autobiographies', 'Autobiographies'), ('Fantasy', 'Fantasy')], max_length=20),
        ),
    ]
