# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170709_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='people_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
