# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_people_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='affiliators_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('moble', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='distributors_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('moble', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
