# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_affiliators_detail_distributors_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliators_detail',
            old_name='moble',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='distributors_detail',
            old_name='moble',
            new_name='mobile',
        ),
    ]
