# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20170711_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_detail',
            name='show_on_main_page',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
