# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_want_to_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_detail',
            name='amazon_hardcover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='amazon_kindle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='amazon_paperback',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='asin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='flipkart_hardcover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='flipkart_kindle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='flipkart_paperback',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='author_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='category',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Competitive', 'Competitive'), ('Science fiction', 'Science fiction'), ('Satire', 'Satire'), ('Drama', 'Drama'), ('Action and Adventure', 'Action and Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Self help', 'Self help'), ('Health', 'Health'), ('Guide', 'Guide'), ('Travel', 'Travel'), ("Children's", "Children's"), ('Religion, Spirituality & New Age', 'Religion, Spirituality & New Age'), ('Science', 'Science'), ('History', 'History'), ('Math', 'Math'), ('Anthology', 'Anthology'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer books', 'Prayer books'), ('Series', 'Series'), ('Trilogy', 'Trilogy'), ('Biographies', 'Biographies'), ('Autobiographies', 'Autobiographies'), ('Fantasy', 'Fantasy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
