# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20170712_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_detail',
            name='amazon_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='flipkart_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
