# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20170712_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_detail',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
