# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20170712_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_detail',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author_detail',
            name='google_plus_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author_detail',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author_detail',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
