# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20170712_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_detail',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
