# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20170714_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_detail',
            name='author_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='amazon_hardcover',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='amazon_kindle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='amazon_paperback',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='book_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='flipkart_hardcover',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='flipkart_kindle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='flipkart_paperback',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='mrp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='selling_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
